# Generated by Django 2.2.3 on 2020-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionservice', '0002_auto_20200930_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionservice',
            name='covid_affected',
            field=models.CharField(blank=True, choices=[('yes_en', 'Yes'), ('no_en', 'No'), ('yes_ro', 'Da'), ('no_ro', 'Nu')], max_length=3, null=True, verbose_name='Are the measures taken in the context of limiting COVID-19 infection affecting you?'),
        ),
        migrations.AlterField(
            model_name='productionservice',
            name='main_effect',
            field=models.CharField(blank=True, choices=[('scaderea_vanzarilor_en', 'Scăderea vânzărilor'), ('scaderea_cifrei_en', 'Scăderea cifrei de afaceri'), ('disponibilizari_en', 'Disponibilizări'), ('intarzieri_en', 'Întârzieri la plata furnizorilor'), ('dificultati_en', 'Dificultăţi la încasare'), ('restrangerea_en', 'Restrângerea activității'), ('suspendarea_en', 'Suspendarea temporară a activităţii'), ('inchiderea_en', 'Închiderea firmei'), ('reprofilare_en', 'Reprofilare'), ('scaderea_vanzarilor_ro', 'Scăderea vânzărilor'), ('scaderea_cifrei_ro', 'Scăderea cifrei de afaceri'), ('disponibilizari_ro', 'Disponibilizări'), ('intarzieri_ro', 'Întârzieri la plata furnizorilor'), ('dificultati_ro', 'Dificultăţi la încasare'), ('restrangerea_ro', 'Restrângerea activității'), ('suspendarea_ro', 'Suspendarea temporară a activităţii'), ('inchiderea_ro', 'Închiderea firmei'), ('reprofilare_ro', 'Reprofilare')], max_length=19, null=True, verbose_name='The main effect is'),
        ),
        migrations.AlterField(
            model_name='productionservice',
            name='toggle',
            field=models.CharField(blank=True, choices=[('gps_en', 'Use GPS'), ('interactive_en', 'Point on Map'), ('manual_en', 'Enter Manually'), ('gps_ro', 'Folosește GPS'), ('interactive_ro', 'Punct pe hartă'), ('manual_ro', 'Introducere manuală')], max_length=11, null=True, verbose_name='Location Mode'),
        ),
        migrations.AlterField(
            model_name='productionservice',
            name='type',
            field=models.CharField(blank=True, choices=[('certificate_en', 'Certificate of producer'), ('small_company_en', 'Small company'), ('small_gardening_en', 'Small gardening'), ('certificate_ro', 'Deținător de certificat de producător'), ('small_company_ro', 'Companie mică'), ('small_gardening_ro', 'Producător local')], max_length=15, null=True, verbose_name='Type'),
        ),
    ]
