# Generated by Django 2.2.3 on 2020-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersupplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersupplier',
            name='irrigation_supply',
            field=models.CharField(blank=True, choices=[('source_en', 'From source'), ('underground_en', 'Underground water'), ('source_ro', 'Din sursă'), ('underground_ro', 'Apă subterană')], max_length=11, null=True, verbose_name='Irrigation supply'),
        ),
        migrations.AlterField(
            model_name='watersupplier',
            name='toggle',
            field=models.CharField(blank=True, choices=[('gps_en', 'Use GPS'), ('interactive_en', 'Point on Map'), ('manual_en', 'Enter Manually'), ('gps_ro', 'Folosește GPS'), ('interactive_ro', 'Punct pe hartă'), ('manual_ro', 'Introducere manuală')], max_length=11, null=True, verbose_name='Location Mode'),
        ),
    ]
