# Generated by Django 2.2.3 on 2020-12-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersupplier', '0003_auto_20201202_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersupplier',
            name='irrigation_supply',
            field=models.CharField(blank=True, choices=[('source_en', 'From source'), ('underground_en', 'Underground water'), ('source_ro', 'Din sursă'), ('underground_ro', 'Apă subterană')], max_length=14, null=True, verbose_name='Irrigation supply'),
        ),
    ]
