# Generated by Django 2.2.3 on 2020-11-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='other_function',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='main_attraction',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_feature_add_by_others',
            field=models.IntegerField(blank=True, null=True, verbose_name='Possibility to see the information added by other users'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_feature_add_comment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leave a comment (open question)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_feature_add_producer_seller',
            field=models.IntegerField(blank=True, null=True, verbose_name='Possibility to add a local food producer/seller on the map'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_feature_see_energy_usage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Access to information on energy usage'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_feature_see_producer_seller',
            field=models.IntegerField(blank=True, null=True, verbose_name='Access to information on local food producers/sellers'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_feature_see_water_supplier',
            field=models.IntegerField(blank=True, null=True, verbose_name='Access to information on water supplier'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_info_consumer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Information about consumers and consumers profile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_info_energy_usage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Evaluations of energy usage'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_info_producer_seller',
            field=models.IntegerField(blank=True, null=True, verbose_name='Information on local food producers/sellers '),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_info_production_service',
            field=models.IntegerField(blank=True, null=True, verbose_name='Information on production service '),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_info_storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Information on storage points'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rank_info_water_supplier',
            field=models.IntegerField(blank=True, null=True, verbose_name='Information about water supplier'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='usefulness',
            field=models.CharField(blank=True, choices=[('definitely_yes', 'Definitely yes'), ('rather_yes', 'Rather yes'), ('no_opinion', 'I have no opinion'), ('rather_not', 'Rather not'), ('definitely_not', 'Definitely not')], max_length=14, null=True, verbose_name='Do you think that the data collected through the application can be useful for a better representation of local producers and small gardeners?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='usability',
            field=models.CharField(blank=True, choices=[('strong_agree', 'I strongly agree'), ('rather_agree', 'I&#x27;d rather agree'), ('undecided', 'Neither disagree nor agree'), ('rather_disagree', 'I&#x27;d rather disagree'), ('strong_disagree', 'I strongly disagree')], max_length=15, null=True, verbose_name='The application is easy to use'),
        ),
    ]
