# Generated by Django 2.2.3 on 2020-12-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20201120_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='attractiveness',
            field=models.CharField(blank=True, choices=[('strong_agree_en', 'I strongly agree'), ('rather_agree_en', 'I&#x27;d rather agree'), ('undecided_en', 'Neither disagree nor agree'), ('rather_disagree_en', 'I&#x27;d rather disagree'), ('strong_disagree_en', 'I strongly disagree'), ('strong_agree_ro', 'Total de acord'), ('rather_agree_ro', 'De acord'), ('undecided_ro', 'Indecis'), ('rather_disagree_ro', 'Nu sunt de acord'), ('strong_disagree_ro', 'Dezacord total')], max_length=15, null=True, verbose_name='The application is visually (graphically) attractive'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='clarity',
            field=models.CharField(blank=True, choices=[('strong_agree_en', 'I strongly agree'), ('rather_agree_en', 'I&#x27;d rather agree'), ('undecided_en', 'Neither disagree nor agree'), ('rather_disagree_en', 'I&#x27;d rather disagree'), ('strong_disagree_en', 'I strongly disagree'), ('strong_agree_ro', 'Total de acord'), ('rather_agree_ro', 'De acord'), ('undecided_ro', 'Indecis'), ('rather_disagree_ro', 'Nu sunt de acord'), ('strong_disagree_ro', 'Dezacord total')], max_length=15, null=True, verbose_name='Instruction on how to use the application is easy to understand'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='maps',
            field=models.CharField(blank=True, choices=[('strong_agree_en', 'I strongly agree'), ('rather_agree_en', 'I&#x27;d rather agree'), ('undecided_en', 'Neither disagree nor agree'), ('rather_disagree_en', 'I&#x27;d rather disagree'), ('strong_disagree_en', 'I strongly disagree'), ('strong_agree_ro', 'Total de acord'), ('rather_agree_ro', 'De acord'), ('undecided_ro', 'Indecis'), ('rather_disagree_ro', 'Nu sunt de acord'), ('strong_disagree_ro', 'Dezacord total')], max_length=15, null=True, verbose_name='Maps help to use the application'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='usability',
            field=models.CharField(blank=True, choices=[('strong_agree_en', 'I strongly agree'), ('rather_agree_en', 'I&#x27;d rather agree'), ('undecided_en', 'Neither disagree nor agree'), ('rather_disagree_en', 'I&#x27;d rather disagree'), ('strong_disagree_en', 'I strongly disagree'), ('strong_agree_ro', 'Total de acord'), ('rather_agree_ro', 'De acord'), ('undecided_ro', 'Indecis'), ('rather_disagree_ro', 'Nu sunt de acord'), ('strong_disagree_ro', 'Dezacord total')], max_length=15, null=True, verbose_name='The application is easy to use'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='usefulness',
            field=models.CharField(blank=True, choices=[('definitely_yes_en', 'Definitely yes'), ('rather_yes_en', 'Rather yes'), ('no_opinion_en', 'I have no opinion'), ('rather_not_en', 'Rather not'), ('definitely_not_en', 'Definitely not'), ('definitely_yes_ro', 'Total de acord'), ('rather_yes_ro', 'De acord'), ('no_opinion_ro', 'Indecis'), ('rather_not_ro', 'Nu sunt de acord'), ('definitely_not_ro', 'Dezacord total')], max_length=14, null=True, verbose_name='Do you think that the data collected through the application can be useful for a better representation of local producers and small gardeners?'),
        ),
    ]
