# Generated by Django 2.2.3 on 2020-06-23 10:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energyusage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(blank=True, choices=[('national', 'National system'), ('renewable', 'Renewable'), ('both', 'Both')], max_length=9, null=True, verbose_name='What type of energy do you use?')),
                ('more_renewable', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True, verbose_name='Would you like to use more renewable energy?')),
                ('renewable_type', models.CharField(blank=True, choices=[('solar', 'Solar'), ('wind', 'Wind'), ('water', 'Water'), ('geothermal', 'Geothermal'), ('bio', 'Bio'), ('other', 'Other')], max_length=10, null=True, verbose_name='What type of renewable energy do you use?')),
                ('toggle', models.CharField(blank=True, choices=[('gps', 'Use GPS'), ('interactive', 'Point on Map'), ('manual', 'Enter Manually')], max_length=11, null=True, verbose_name='Location Mode')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='GPS Accuracy')),
            ],
            options={
                'verbose_name': 'energyusage',
                'verbose_name_plural': 'energyusages',
            },
        ),
    ]
