# Generated by Django 2.2.3 on 2020-12-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20201202_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='big_chain_store',
            field=models.CharField(blank=True, choices=[('1_en', '1'), ('3_en', 'ca. 3'), ('more_en', 'More'), ('1_ro', '1'), ('3_ro', 'cca 3'), ('more_ro', 'Mai multe')], max_length=7, null=True, verbose_name='Big store chains'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='bio',
            field=models.CharField(blank=True, choices=[('frequently_en', 'Frequently'), ('sometimes_en', 'Sometimes'), ('no_use_en', 'No use'), ('frequently_ro', 'Frecvent'), ('sometimes_ro', 'Uneori'), ('no_use_ro', 'Niciodata')], max_length=13, null=True, verbose_name='Bio products use'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male_en', 'Male'), ('female_en', 'Female'), ('male_ro', 'Masculin'), ('female_ro', 'Feminin')], max_length=9, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='income',
            field=models.CharField(blank=True, choices=[('less_1500_en', '&lt; 1500 / family member'), ('more_1500_en', '&gt; 1500 / family member'), ('na_en', 'No answer'), ('less_1500_ro', 'Sub 1500/per membru de familie'), ('more_1500_ro', 'Peste 1500/per membru de familie'), ('na_ro', 'Nu doresc sa răspund')], max_length=12, null=True, verbose_name='Income (Euro)'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='local',
            field=models.CharField(blank=True, choices=[('frequently_en', 'Frequently'), ('sometimes_en', 'Sometimes'), ('no_use_en', 'No use'), ('frequently_ro', 'Frecvent'), ('sometimes_ro', 'Uneori'), ('no_use_ro', 'Niciodata')], max_length=13, null=True, verbose_name='Local/national products use'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='local_chain_store',
            field=models.CharField(blank=True, choices=[('1_en', '1'), ('3_en', 'ca. 3'), ('more_en', 'More'), ('1_ro', '1'), ('3_ro', 'cca 3'), ('more_ro', 'Mai multe')], max_length=7, null=True, verbose_name='Local chain stores'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='market',
            field=models.CharField(blank=True, choices=[('1_en', '1'), ('3_en', 'ca. 3'), ('more_en', 'More'), ('1_ro', '1'), ('3_ro', 'cca 3'), ('more_ro', 'Mai multe')], max_length=7, null=True, verbose_name='Market'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='priorization',
            field=models.CharField(blank=True, choices=[('price_en', 'Price'), ('ecological_impact_en', 'Ecological impact'), ('aquisition_time_en', 'Time for aquisition'), ('health_impact_en', 'Health impact'), ('price_ro', 'Prețul'), ('ecological_impact_ro', 'Impactul ecologic'), ('aquisition_time_ro', 'Timpul consumat pentru cumpărături (distanța până la magazin)'), ('health_impact_ro', 'Impactul asupra sănătății')], max_length=20, null=True, verbose_name='Priorization in food choice'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='small_shop',
            field=models.CharField(blank=True, choices=[('1_en', '1'), ('3_en', 'ca. 3'), ('more_en', 'More'), ('1_ro', '1'), ('3_ro', 'cca 3'), ('more_ro', 'Mai multe')], max_length=7, null=True, verbose_name='Small shops'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='transport',
            field=models.CharField(blank=True, choices=[('car_en', 'Personal car'), ('public_en', 'Public transport'), ('bike_en', 'By bike'), ('foot_en', 'By foot'), ('car_ro', 'Auto personal'), ('public_ro', 'Transport public'), ('bike_ro', 'Bicicletă'), ('foot_ro', 'Pedestru')], max_length=9, null=True, verbose_name='Main transport'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='waste_water',
            field=models.CharField(blank=True, choices=[('sewage_en', 'Sewage system'), ('septic_en', 'Septic tanks'), ('no_treatment_en', 'No treatment at all'), ('sewage_ro', 'Sistem centralizat de canalizare'), ('septic_ro', 'Fosă septică'), ('no_treatment_ro', 'Nici unul')], max_length=15, null=True, verbose_name='Waste water'),
        ),
    ]
