# Generated by Django 2.2.3 on 2020-06-04 09:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salepoint', '0001_initial'),
        ('storagepoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('type', models.CharField(blank=True, choices=[('certificate', 'Certificate of producer'), ('small_company', 'Small company'), ('small_gardening', 'Small gardening')], max_length=15, null=True, verbose_name='Type')),
                ('product', models.TextField(blank=True, null=True, verbose_name='Main product(s)')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Telephone')),
                ('email', models.TextField(blank=True, null=True, verbose_name='E-mail')),
                ('website', models.TextField(blank=True, null=True, verbose_name='Website')),
                ('toggle', models.CharField(blank=True, choices=[('gps', 'Use GPS'), ('interactive', 'Point on Map'), ('manual', 'Enter Manually')], max_length=11, null=True, verbose_name='Location Mode')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='GPS Accuracy')),
                ('irrigation_use', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True, verbose_name='Do you use water for irrigation?')),
                ('irrigation_interest', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True, verbose_name='If not, do you have interest?')),
                ('irrigation_quantity', models.FloatField(blank=True, null=True, verbose_name='Quantity (in m³ per year)')),
                ('irrigation_quality', models.CharField(blank=True, choices=[('source', 'From source'), ('underground', 'Underground water')], max_length=11, null=True, verbose_name='Water quality')),
                ('electrical_consumption', models.FloatField(blank=True, null=True, verbose_name='Average electrical consumption (in kWh per year)')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance: producer → storage → shop')),
                ('production', models.FloatField(blank=True, null=True, verbose_name='Production (in kg/ha per year)')),
                ('surface', models.FloatField(blank=True, null=True, verbose_name='Surface (in ha)')),
                ('use', models.CharField(blank=True, choices=[('homefood', 'Homefood'), ('other', 'Other')], max_length=8, null=True, verbose_name='Uses')),
                ('fertilizer', models.CharField(blank=True, choices=[('natural', 'Natural'), ('artificial', 'Artificial')], max_length=10, null=True, verbose_name='Use of fertilizer')),
                ('salepoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salepoint.Salepoint', verbose_name='Sale point')),
                ('storagepoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storagepoint.Storagepoint', verbose_name='Storage point')),
            ],
            options={
                'verbose_name': 'producer',
                'verbose_name_plural': 'producers',
            },
        ),
    ]
